### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by ghost** [meain/stag#1]
How to set the environment variables for spotify client ID and all...?

**Comment by meain** [comment]
You can generate the client id and secret and others as documented [here](https://developer.spotify.com/documentation/general/guides/app-settings/#register-your-app). Once that is available, you can set the client id and secret in your `.bashrc` or `.zshrc` file by adding:

```
export SPOTIFY_CLIENT_ID="..."
export SPOTIFY_CLIENT_SECRET="..."
export SPOTIFY_USERNAME="..."
```
